# Copyright (C) 2006 Martin Willi
# Hochschule fuer Technik Rapperswil
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#

LIB_DIR= $(MAIN_DIR)lib/

LIB_OBJS+= $(BUILD_DIR)types.o
$(BUILD_DIR)types.o :			$(LIB_DIR)types.c $(LIB_DIR)types.h
								$(CC) $(CFLAGS) -c -o $@ $<

LIB_OBJS+= $(BUILD_DIR)definitions.o
$(BUILD_DIR)definitions.o :		$(LIB_DIR)definitions.c $(LIB_DIR)definitions.h
								$(CC) $(CFLAGS) -c -o $@ $<

LIB_OBJS+= $(BUILD_DIR)library.o
$(BUILD_DIR)library.o :			$(LIB_DIR)library.c
								$(CC) $(CFLAGS) -c -o $@ $<

include $(MAIN_DIR)lib/crypto/Makefile.transforms
include $(MAIN_DIR)lib/utils/Makefile.utils
include $(MAIN_DIR)lib/asn1/Makefile.asn1
