.TH _PLUTORUN 8 "25 Apr 2002"
.\"
.\" RCSID $Id: _plutorun.8,v 1.1 2004/03/15 20:35:27 as Exp $
.\"
.SH NAME
ipsec _plutorun \- internal script to start pluto
.SH DESCRIPTION
.I _plutorun
is called by
.B _realsetup
to configure and bring up 
.B ipsec_pluto(8).
It calls 
.B _plutoload
to invoke pluto, and watches to makes sure that pluto is restarted if it fails.
.SH "SEE ALSO"
ipsec(8), ipsec_setup(8), ipsec__realsetup(8), ipsec__plutoload(8), ipsec_pluto(8).
.SH HISTORY
Man page written for the Linux FreeS/WAN project <http://www.freeswan.org/>
by Michael Richardson. Original program written by Henry Spencer.
.\"
.\" $Log: _plutorun.8,v $
.\" Revision 1.1  2004/03/15 20:35:27  as
.\" added files from freeswan-2.04-x509-1.5.3
.\"
.\" Revision 1.2  2002/04/29 22:39:31  mcr
.\" 	added basic man page for all internal commands.
.\"
.\" Revision 1.1  2002/04/26 01:21:43  mcr
.\" 	while tracking down a missing (not installed) /etc/ipsec.conf,
.\" 	MCR has decided that it is not okay for each program subdir to have
.\" 	some subset (determined with -f) of possible files.
.\" 	Each subdir that defines $PROGRAM, MUST have a PROGRAM.8 file as well as a PROGRAM file.
.\" 	Optional PROGRAM.5 files have been added to the makefiles.
.\"
.\"
.\"
