#!/bin/bash

if [ `id -u` != 0 ];
then
	echo "! you must be root to run $0"
	exit
fi

DIR=`dirname $0`

. $DIR/function.sh

[ -f $DIR/../testing.conf ] || die "!! Configuration file 'testing.conf' not found"
. $DIR/../testing.conf

# additional packages
EXTRAS=build-essential,gperf,libgmp-dev,libldap2-dev,libcurl4-openssl-dev,libxml2-dev,libtspi-dev,libsqlite3-dev,openssh-server,tcpdump,psmisc,openssl,vim,sqlite3,conntrack,gdb,cmake,libxerces-c2-dev,libltdl-dev,liblog4cxx10-dev,libboost-thread-dev,libboost-system-dev,git-core
SERVICES="isc-dhcp-server apache2 slapd"
PACKAGES=$EXTRAS,${SERVICES// /,}
CACHEDIR=$BUILDDIR/cache
APTCACHE=$LOOPDIR/var/cache/apt/archives

mkdir -p $LOOPDIR
mkdir -p $BUILDDIR
mkdir -p $CACHEDIR
rm -f $ROOTFS

echo "`date`, building $ROOTFS" >>$LOGFILE
echo "Building base image"
log_action "Creating image $ROOTFS"
execute "dd if=/dev/null of=$ROOTFS bs=1M seek=$ROOTFSSIZE count=1"

log_action "Creating ext3 filesystem"
execute "mkfs.ext3 -F $ROOTFS"

log_action "Mounting image to $LOOPDIR"
execute "mount -o loop $ROOTFS $LOOPDIR"

log_action "Mounting cache to $CACHEDIR"
mkdir -p $APTCACHE
execute "mount -o bind $CACHEDIR $APTCACHE"

log_action "Running debootstrap ($ROOTFSSUITE, $ROOTFSARCH)"
execute "debootstrap --arch=$ROOTFSARCH --include=$PACKAGES $ROOTFSSUITE $LOOPDIR $ROOTFSMIRROR"

log_action "Disabling root password"
execute_chroot "passwd -d root"

for service in $SERVICES
do
	log_action "Stopping service $service"
	execute_chroot "/etc/init.d/$service stop"
	log_action "Disabling service $service"
	execute_chroot "update-rc.d -f $service remove"
done

execute "umount -l $APTCACHE" 0
execute "umount -l $LOOPDIR" 0
