#!/bin/bash
# create UML host file systems
#
# Copyright (C) 2004  Eric Marchionni, Patrik Rayo
# Zuercher Hochschule Winterthur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# RCSID $Id: build-umlhostfs,v 1.3 2006/03/30 21:20:27 as Exp $

DIR=`dirname $0`

source $DIR/function.sh

[ -f $DIR/../testing.conf ] || die "!! Configuration file 'testing.conf' not found."

source $DIR/../testing.conf

cd $BUILDDIR/root-fs

[ -f gentoo-fs ] || die "!! Root file system 'gentoo-fs' not found."

if [ ! -d $BUILDDIR ]
then
    cecho-n " * Directory '$BUILDDIR' does not exist..creating.."
    mkdir $BUILDDIR
    cgecho "done"
fi

LOGFILE=${BUILDDIR}/testing.log

if [ ! -f $LOGFILE ]
then
    cecho-n " * Logfile '$LOGFILE' does not exist..creating.."
    touch $LOGFILE
    cgecho "done"
fi

LOOPDIR=loop

if [ ! -d $LOOPDIR ]
then
    mkdir $LOOPDIR
fi

cecho-n " * Creating root filesystem for.."

if [ "$#" -eq 0 ]
then
    HOSTS=$STRONGSWANHOSTS
else
    HOSTS=$*
fi

for host in $HOSTS
do
    cecho-n "$host.."
    cp gentoo-fs gentoo-fs-$host
    mount -o loop gentoo-fs-$host $LOOPDIR
    cp -rfp $BUILDDIR/hosts/${host}/etc $LOOPDIR
    if [ "$host" = "winnetou" ]
    then
    	mkdir $LOOPDIR/var/log/apache2/ocsp
	cp -rfp $UMLTESTDIR/testing/images $LOOPDIR/var/www/localhost/htdocs
        chroot $LOOPDIR /etc/openssl/generate-crl >> $LOGFILE 2>&1
    fi
    chroot $LOOPDIR /etc/init.d/depscan.sh --update >> $LOGFILE 2>&1
    umount $LOOPDIR
done

cgecho "done"
