#!/bin/bash
# create UML host file systems
#
# Copyright (C) 2004  Eric Marchionni, Patrik Rayo
# Zuercher Hochschule Winterthur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

DIR=`dirname $0`

source $DIR/function.sh

[ -f $DIR/../testing.conf ] || die "!! Configuration file 'testing.conf' not found."

source $DIR/../testing.conf

cd $BUILDDIR/root-fs
BASE=$BUILDDIR/base.img

[ -f $BASE ] || die "!! Base image $BASE not found."

if [ ! -d $BUILDDIR ]
then
    cecho-n " * Directory '$BUILDDIR' does not exist..creating.."
    mkdir $BUILDDIR
    cgecho "done"
fi

if [ ! -d $LOOPDIR ]
then
    mkdir $LOOPDIR
fi

cecho-n " * Creating root filesystem for.."

if [ "$#" -eq 0 ]
then
    HOSTS=$STRONGSWANHOSTS
else
    HOSTS=$*
fi

for host in $HOSTS
do
    cecho-n "$host.."
    cp $BASE $host.img
    mount -o loop $host.img $LOOPDIR
    cp -rf $BUILDDIR/hosts/${host}/etc $LOOPDIR
    if [ "$host" = "winnetou" ]
    then
		mkdir $LOOPDIR/var/log/apache2/ocsp
		cp -rf $UMLTESTDIR/testing/images $LOOPDIR/var/www/
		chroot $LOOPDIR ln -s /etc/openssl/certs /var/www/certs
		chroot $LOOPDIR /etc/openssl/generate-crl >> $LOGFILE 2>&1
		chroot $LOOPDIR update-rc.d apache2 defaults >> $LOGFILE 2>&1
		chroot $LOOPDIR update-rc.d slapd defaults >> $LOGFILE 2>&1
		chroot $LOOPDIR rm -rf /var/lib/ldap/*
		chroot $LOOPDIR slapadd -l /etc/ldap/ldif.txt -f /etc/ldap/slapd.conf >> $LOGFILE 2>&1
		chroot $LOOPDIR chown -R openldap:openldap /var/lib/ldap >> $LOGFILE 2>&1
    fi
    sync
    umount $LOOPDIR
done

cgecho "done"
