#!/bin/bash
# Install strongSwan from mounted strongswan-shared tree
#
# Copyright (C) 2006 Martin Willi
# Hochschule fuer Technik Rapperswil
# Copyright (C) 2004  Eric Marchionni, Patrik Rayo
# Zuercher Hochschule Winterthur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#

DIR=`dirname $0`

source $DIR/function.sh

[ -f $DIR/../testing.conf ] || die "Configuration file 'testing.conf' not found"

source $DIR/../testing.conf

cecho "installing strongSwan from shared tree"
cecho-n "  on: "

for host in $STRONGSWANHOSTS
do
    eval HOSTLOGIN="root@`echo $HOSTNAMEIPV4 | sed -n -e "s/^.*${host},//gp" | awk -F, '{ print $1 }' | awk '{ print $1 }'`"
    cecho-n "$host... "
    ssh $HOSTLOGIN 'cd ~/strongswan-shared && make install' > /dev/null
done

cecho
