#!/bin/bash
# stop the UML bridges in the kernel using the brctl command
#
# Copyright (C) 2009  Andreas Steffen
# HSR Hochschule fuer Technik Rapperswil
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

DIR=`dirname $0`

source $DIR/function.sh

# stop umlbr1 and its taps 
#
cecho-n " * Stopping umlbr1 with taps.."
umlbr_del_tap 1 alice
umlbr_del_tap 1 venus
umlbr_del_tap 1 moon
umlbr_del     1
cgecho "done"

# stop umlbr0 and its taps
#
cecho-n " * Stopping umlbr0 with taps.."
umlbr_del_tap 0 alice
umlbr_del_tap 0 moon
umlbr_del_tap 0 carol
umlbr_del_tap 0 winnetou
umlbr_del_tap 0 dave
umlbr_del_tap 0 sun
umlbr_del     0
cgecho "done"

# stop umlbr2 and its taps
#
cecho-n " * Stopping umlbr2 with taps.."
umlbr_del_tap 2 sun
umlbr_del_tap 2 bob
umlbr_del     2
cgecho "done"

