alpine_task:
  container:
    image: alpine:latest

  env:
    TESTS_REDUCED_KEYLENGTHS: yes
    TESTS_NO_IPV6: yes
    LEAK_DETECTIVE: no
    MONOLITHIC: no
    TEST: alpine
    OS_NAME: alpine

  install_script: ./scripts/test.sh deps
  script: ./scripts/test.sh
