#!/bin/bash

. $PWD/scripts/function.sh

rm -f $LOGFILE

if [ $ENABLE_BUILD_BASEIMAGE = "yes" ]
then
	$PWD/scripts/build-baseimage || exit 1
fi

if [ $ENABLE_BUILD_ROOTIMAGE = "yes" ]
then
	$PWD/scripts/build-rootimage || exit 1
fi

if [ $ENABLE_BUILD_GUESTKERNEL = "yes" ]
then
	$PWD/scripts/build-guestkernel || exit 1
fi

if [ $ENABLE_BUILD_UMLHOSTFS = "yes" ]
then
	$PWD/scripts/build-umlhostfs $HOSTS || exit 1
fi
