#!/bin/bash
# Create the strongSwan UML testing environment
#
# Copyright (C) 2004  Eric Marchionni, Patrik Rayo
# Zuercher Hochschule Winterthur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

. $PWD/scripts/function.sh

rm -f $LOGFILE

if [ $ENABLE_BUILD_BASEIMAGE = "yes" ]
then
	$PWD/scripts/build-baseimage
fi

if [ $ENABLE_BUILD_GUESTKERNEL = "yes" ]
then
	$PWD/scripts/build-guestkernel
fi

if [ $ENABLE_BUILD_UMLROOTFS = "yes" ]
then
	$PWD/scripts/build-umlrootfs
fi

if [ $ENABLE_BUILD_UMLHOSTFS = "yes" ]
then
	$PWD/scripts/build-umlhostfs $HOSTS
fi
