#!/bin/bash

. $PWD/scripts/function.sh

rm -f $LOGFILE

if [ $ENABLE_BUILD_BASEIMAGE = "yes" ]
then
	$PWD/scripts/build-baseimage
fi

if [ $ENABLE_BUILD_GUESTKERNEL = "yes" ]
then
	$PWD/scripts/build-guestkernel
fi

if [ $ENABLE_BUILD_UMLROOTFS = "yes" ]
then
	$PWD/scripts/build-umlrootfs
fi

if [ $ENABLE_BUILD_UMLHOSTFS = "yes" ]
then
	$PWD/scripts/build-umlhostfs $HOSTS
fi
