#!/bin/bash
# Start up the specified UML instances and wait for them to finish booting
#
# Copyright (C) 2004  Eric Marchionni, Patrik Rayo
# Zuercher Hochschule Winterthur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

DIR=`dirname $0`

source $DIR/scripts/function.sh

[ -f $DIR/testing.conf ] || die "!! Configuration file 'testing.conf' not found"
[ -d $DIR/hosts ] || die "Directory hosts cannot be found."

source $DIR/testing.conf

if [ "$#" -eq 0 ]
then
    HOSTS=$STRONGSWANHOSTS
else
    HOSTS=$*
fi

#####################################################
# start the uml bridges
#
cecho "Start the uml bridges  (scripts/start-bridges)"
$DIR/scripts/start-bridges


#####################################################
# start the uml instances
#
cecho "Start the uml instances  (scripts/start-umls)"
$DIR/scripts/start-umls $HOSTS
