#!/bin/bash
# Stop all UML instances and UML switches
#
# Copyright (C) 2004  Eric Marchionni, Patrik Rayo
# Zuercher Hochschule Winterthur
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# RCSID $Id: stop-testing,v 1.3 2004/12/07 18:04:57 as Exp $

DIR=`dirname $0`

source $DIR/scripts/function.sh

[ -f $DIR/testing.conf ] || die "No configuration file testing.conf found."

source $DIR/testing.conf

if [ "$#" -eq 0 ]
then
    HOSTS=$STRONGSWANHOSTS
else
    HOSTS=$*
fi

#####################################################
# Shutting down the uml instances
#
cecho-n " * Halting all UML instances.."
for host in $HOSTS
do
    uml_mconsole $host halt &> /dev/null
done
cgecho "done"

#####################################################
# Shutting down the uml switches
#
cecho-n " * Stopping the UML switches.."
killall uml_switch &> /dev/null
rm -f /tmp/umlswitch[012] &> /dev/null 2>&1
cgecho "done"

