.TH IPSEC_SECRETS 8 "31 Aug 2003"
.\" RCSID $Id: secrets.8,v 1.1 2004/03/15 20:35:30 as Exp $
.SH NAME
ipsec secrets \- prompt for PIN codes and passphrases
.SH SYNOPSIS
.B ipsec
.B secrets
.SH DESCRIPTION
.I Secrets
is an alias for
.B ipsec auto --rereadsecrets
and prompts for PIN codes and passphrases protecting private RSA keys.
.SH SEE ALSO
ipsec.secrets(5)
.SH HISTORY
Written for the FreeS/WAN project
<http://www.freeswan.org>
by Andreas Steffen.
.SH BUGS
None
