.TH IPSEC_MAILKEY 8 "21 Feb 2002"
.\" RCSID $Id: mailkey.8,v 1.1 2004/03/15 20:35:28 as Exp $
.SH NAME
ipsec mailkey \- mail DNS records for Opportunistic Encryption
.SH SYNOPSIS
.B ipsec
.B mailkey
\-\-me
my@address.tld
[
.B \-\-reverse
1.2.3.4
] [
.B \-\-forward
hostname.domain.tld
]
.SH DESCRIPTION
.I mailkey
is a meta-program. It generates a script which will attempt to mail the TXT 
records required to enable Opportunistic Encryption (OE).
.PP
An e-mail address for the domain's DNS administrator is derived from SOA records. 
The mail body and destination address are freely editable in the script.
.PP
If no administrator can be located, the output file will not be executable.
.PP
.TP
\fB\-\-me\fP\ \fImy@address.tld\fP
set the Reply-To: address of the mail to be sent.
.TP
\fB\-\-forward\fP\ \fIhostname.domain.tld\fP
the domain name to be used for initator-only OE.  
.TP
\fB\-\-reverse\fP\ \fI1.2.3.4\fP
the IP address to be used for full Opportunistic Encryption.
.PP
Only one of --forward or --reverse may be specified.
.SH FILES
.nf
/etc/ipsec.secrets
.fi
.SH SEE ALSO
ipsec_showhostkey(8), host(8)
.SH HISTORY
Written for the Linux FreeS/WAN project <http://www.freeswan.org> by Sam Sgro.
.SH BUGS
May produce indeterminate results when processing non-routable IPs.
