# Copyright (C) 2005 Jan Hutter, Martin Willi
# Hochschule fuer Technik Rapperswil
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#

CONFIG_DIR= $(CHARON_DIR)config/


CHARON_OBJS+= $(BUILD_DIR)traffic_selector.o
$(BUILD_DIR)traffic_selector.o :			$(CONFIG_DIR)traffic_selector.c $(CONFIG_DIR)traffic_selector.h
											$(CC) $(CFLAGS) -c -o $@ $<

CHARON_OBJS+= $(BUILD_DIR)proposal.o
$(BUILD_DIR)proposal.o :					$(CONFIG_DIR)proposal.c $(CONFIG_DIR)proposal.h
											$(CC) $(CFLAGS) -c -o $@ $<

CHARON_OBJS+= $(BUILD_DIR)configuration.o
$(BUILD_DIR)configuration.o :				$(CONFIG_DIR)configuration.c $(CONFIG_DIR)configuration.h
											$(CC) $(CFLAGS) -c -o $@ $<

include $(CONFIG_DIR)connections/Makefile.connections
include $(CONFIG_DIR)credentials/Makefile.credentials
include $(CONFIG_DIR)policies/Makefile.policies