.TH look 8 "25 Apr 2002"
.\"
.\" RCSID $Id: look.8,v 1.1 2004/03/15 20:35:28 as Exp $
.\"
.SH NAME
ipsec look \- get a quick summary of FreeS/WAN status
.SH SYNOPSIS
.I look
is used to get a quick overview of what the status of FreeSWAN is.
It is equivalent to:
\ \ \ ipsec eroute

\ \ \ ipsec spigrp

\ \ \ ipsec tncfg

\ \ \ ipsec spi

\ \ \ netstat -rn

.LP
However a bit of processing is done to combine the outputs.
.SH "SEE ALSO"
ipsec(8), ipsec_tncfg(8), ipsec_spi(8), ipsec_spigrp(8), ipsec_eroute(5),
netstat(8).
.SH HISTORY
Man page written for the Linux FreeS/WAN project <http://www.freeswan.org/>
by Michael Richardson. Original program written by Henry Spencer.
.\"
.\" $Log: look.8,v $
.\" Revision 1.1  2004/03/15 20:35:28  as
.\" added files from freeswan-2.04-x509-1.5.3
.\"
.\" Revision 1.2  2002/04/29 22:39:31  mcr
.\" 	added basic man page for all internal commands.
.\"
.\" Revision 1.1  2002/04/26 01:21:43  mcr
.\" 	while tracking down a missing (not installed) /etc/ipsec.conf,
.\" 	MCR has decided that it is not okay for each program subdir to have
.\" 	some subset (determined with -f) of possible files.
.\" 	Each subdir that defines $PROGRAM, MUST have a PROGRAM.8 file as well as a PROGRAM file.
.\" 	Optional PROGRAM.5 files have been added to the makefiles.
.\"
.\"
.\"
