
dumm:	dumm.c dumm.h guest.c guest.h iface.c iface.h mconsole.c mconsole.h main.c
	gcc -o dumm dumm.c guest.c iface.c mconsole.c main.c -lreadline -lstrongswan -I../libstrongswan/ -g -O2 -Wall -Wno-format -Wno-strict-aliasing
