.TH IPSEC_TRAP_SENDCOUNT 5 "19 Jun 2003"
.\"
.\" RCSID $Id: trap_sendcount.5,v 1.1 2004/03/15 20:35:30 as Exp $
.\"
.SH NAME
trap_sendcount \- KLIPS statistic on number of successful ACQUIREs
.SH SYNOPSIS
.B cat
.B /proc/net/ipsec/stats/trap_sendcount
.SH DESCRIPTION
.I /proc/net/ipsec/stats/trap_sendcount
is a read-only file. It contains a hexadecimal number which records the
number of successful PF_ACQUIRE messages that were sent.
.LP
.SH "FILES"
/proc/net/ipsec/stats/trap_sendcount
.SH "SEE ALSO"
ipsec(8), ipsec_pf_key(5), trap_count(5), pluto(8)
.SH HISTORY
Written for the Linux FreeS/WAN project
<http://www.freeswan.org/>
by Michael C. Richardson <mcr@freeswan.org>
.\"
.\" $Log: trap_sendcount.5,v $
.\" Revision 1.1  2004/03/15 20:35:30  as
.\" added files from freeswan-2.04-x509-1.5.3
.\"
.\" Revision 1.1  2003/06/20 02:56:20  mcr
.\" 	added documentation for /proc/net/ipsec/stats/trap_* and
.\" 	amendments to test cases.
.\"
.\"
.\"
