.TH IPSEC_TRAP_COUNT 5 "19 Jun 2003"
.\"
.\" RCSID $Id: trap_count.5,v 1.1 2004/03/15 20:35:30 as Exp $
.\"
.SH NAME
trap_count \- KLIPS statistic on number of ACQUIREs
.SH SYNOPSIS
.B cat
.B /proc/net/ipsec/stats/trap_count
.SH DESCRIPTION
.I /proc/net/ipsec/stats/trap_count
is a read-only file. It contains a hexadecimal number which records the
number of attempts to send PF_ACQUIRE messages. Only those recorded by
trap_sendcount were actually successfully passed to userland. Note that the
userland may still have lost them on its own.
.LP
.SH "FILES"
/proc/net/ipsec/stats/trap_sendcount
.SH "SEE ALSO"
ipsec(8), ipsec_pf_key(5), trap_sendcount(5), pluto(8)
.SH HISTORY
Written for the Linux FreeS/WAN project
<http://www.freeswan.org/>
by Michael C. Richardson <mcr@freeswan.org>
.\"
.\" $Log: trap_count.5,v $
.\" Revision 1.1  2004/03/15 20:35:30  as
.\" added files from freeswan-2.04-x509-1.5.3
.\"
.\" Revision 1.1  2003/06/20 02:56:20  mcr
.\" 	added documentation for /proc/net/ipsec/stats/trap_* and
.\" 	amendments to test cases.
.\"
.\"
.\"
