/**
 * @file signer.h
 * 
 * @brief Generic interface for integrity algorithms
 * 
 */

/*
 * Copyright (C) 2005 Jan Hutter, Martin Willi
 * Hochschule fuer Technik Rapperswil
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 */

#ifndef SIGNER_H_
#define SIGNER_H_

#include "../../payloads/transform_substructure.h"


/**
 * Object representing a diffie hellman exchange
 */
typedef struct signer_s signer_t;

struct signer_s {
	/**
	 * @brief generates pseudo random bytes and writes them
	 * in the buffer
	 * 
	 * @param this			calling signer
	 * @param seed			a chunk containing the seed for the next bytes
	 * @param [out]buffer	pointer where the generated bytes will be written
	 * @return				
	 * 						- SUCCESS in any case
	 */
	status_t (*get_signature) (signer_t *this, chunk_t data, u_int8_t *buffer);
	
	/**
	 * @brief generates pseudo random bytes and allocate space for them
	 * 
	 * @param this			calling signer
	 * @param seed			a chunk containing the seed for the next bytes
	 * @param [out]chunk	chunk which will hold generated bytes
	 * @return				
	 * 						- SUCCESS in any case
	 * 						- OUT_OF_RES if space could not be allocated
	 */
	status_t (*allocate_signature) (signer_t *this, chunk_t data, chunk_t *chunk);
	
	/**
	 * @brief generates pseudo random bytes and writes them
	 * in the buffer
	 * 
	 * @param this			calling signer
	 * @param seed			a chunk containing the seed for the next bytes
	 * @param [out]buffer	pointer where the generated bytes will be written
	 * @return				
	 * 						- SUCCESS in any case
	 */
	status_t (*verify_signature) (signer_t *this, chunk_t data, chunk_t signature, bool *valid);
	
	/**
	 * @brief get the block size of this signer
	 * 
	 * @param this			calling signer
	 * @return				block size in bytes
	 */
	size_t (*get_block_size) (signer_t *this);
	
	/**
	 * @brief Set the key for this signer
	 * 
	 * @param this			calling signer
	 * @return				block size in bytes
	 */
	status_t (*set_key) (signer_t *this, chunk_t key);
	
	/**
	 * @brief Destroys a signer object.
	 *
	 * @param this 	signer_t object to destroy
	 * @return 		
	 * 				SUCCESS in any case
	 */
	status_t (*destroy) (signer_t *this);
};

/**
 * Creates a new signer_t object
 * 
 * @param pseudo_random_function	Algorithm to use
 * @return
 * 									- signer_t if successfully
 * 									- NULL if out of ressources or signer not supported
 */
signer_t *signer_create(integrity_algorithm_t integrity_algorithm);

#endif /*SIGNER_H_*/
