# Copyright (C) 2005 Jan Hutter, Martin Willi
# Hochschule fuer Technik Rapperswil
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#

PAYLOADS_DIR= $(ENCODING_DIR)payloads/

OBJS+= $(BUILD_DIR)encodings.o
$(BUILD_DIR)encodings.o :				$(PAYLOADS_DIR)encodings.c $(PAYLOADS_DIR)encodings.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)ike_header.o
$(BUILD_DIR)ike_header.o :				$(PAYLOADS_DIR)ike_header.c $(PAYLOADS_DIR)ike_header.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)ke_payload.o
$(BUILD_DIR)ke_payload.o :				$(PAYLOADS_DIR)ke_payload.c $(PAYLOADS_DIR)ke_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)nonce_payload.o
$(BUILD_DIR)nonce_payload.o :			$(PAYLOADS_DIR)nonce_payload.c $(PAYLOADS_DIR)nonce_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)notify_payload.o
$(BUILD_DIR)notify_payload.o :			$(PAYLOADS_DIR)notify_payload.c $(PAYLOADS_DIR)notify_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)id_payload.o
$(BUILD_DIR)id_payload.o :				$(PAYLOADS_DIR)id_payload.c $(PAYLOADS_DIR)id_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<
										
OBJS+= $(BUILD_DIR)auth_payload.o
$(BUILD_DIR)auth_payload.o :				$(PAYLOADS_DIR)auth_payload.c $(PAYLOADS_DIR)auth_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<
										
OBJS+= $(BUILD_DIR)cert_payload.o
$(BUILD_DIR)cert_payload.o :			$(PAYLOADS_DIR)cert_payload.c $(PAYLOADS_DIR)cert_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)certreq_payload.o
$(BUILD_DIR)certreq_payload.o :			$(PAYLOADS_DIR)certreq_payload.c $(PAYLOADS_DIR)certreq_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)delete_payload.o
$(BUILD_DIR)delete_payload.o :			$(PAYLOADS_DIR)delete_payload.c $(PAYLOADS_DIR)delete_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)vendor_id_payload.o
$(BUILD_DIR)vendor_id_payload.o :		$(PAYLOADS_DIR)vendor_id_payload.c $(PAYLOADS_DIR)vendor_id_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<
										
OBJS+= $(BUILD_DIR)cp_payload.o
$(BUILD_DIR)cp_payload.o :				$(PAYLOADS_DIR)cp_payload.c $(PAYLOADS_DIR)cp_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<
										
OBJS+= $(BUILD_DIR)configuration_attribute.o
$(BUILD_DIR)configuration_attribute.o :	$(PAYLOADS_DIR)configuration_attribute.c $(PAYLOADS_DIR)configuration_attribute.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)eap_payload.o
$(BUILD_DIR)eap_payload.o :				$(PAYLOADS_DIR)eap_payload.c $(PAYLOADS_DIR)eap_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<
										
OBJS+= $(BUILD_DIR)unknown_payload.o
$(BUILD_DIR)unknown_payload.o :			$(PAYLOADS_DIR)unknown_payload.c $(PAYLOADS_DIR)unknown_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)ts_payload.o
$(BUILD_DIR)ts_payload.o :				$(PAYLOADS_DIR)ts_payload.c $(PAYLOADS_DIR)ts_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)traffic_selector_substructure.o
$(BUILD_DIR)traffic_selector_substructure.o :	$(PAYLOADS_DIR)traffic_selector_substructure.c $(PAYLOADS_DIR)traffic_selector_substructure.h
												$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)payload.o
$(BUILD_DIR)payload.o :					$(PAYLOADS_DIR)payload.c $(PAYLOADS_DIR)payload.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)proposal_substructure.o
$(BUILD_DIR)proposal_substructure.o :	$(PAYLOADS_DIR)proposal_substructure.c $(PAYLOADS_DIR)proposal_substructure.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)sa_payload.o
$(BUILD_DIR)sa_payload.o :				$(PAYLOADS_DIR)sa_payload.c $(PAYLOADS_DIR)sa_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)transform_attribute.o
$(BUILD_DIR)transform_attribute.o :		$(PAYLOADS_DIR)transform_attribute.c $(PAYLOADS_DIR)transform_attribute.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)transform_substructure.o
$(BUILD_DIR)transform_substructure.o :	$(PAYLOADS_DIR)transform_substructure.c $(PAYLOADS_DIR)transform_substructure.h
										$(CC) $(CFLAGS) -c -o $@ $<

OBJS+= $(BUILD_DIR)encryption_payload.o
$(BUILD_DIR)encryption_payload.o :		$(PAYLOADS_DIR)encryption_payload.c $(PAYLOADS_DIR)encryption_payload.h
										$(CC) $(CFLAGS) -c -o $@ $<
								
