#! /bin/sh
# determine kernel version code, mostly for use in RPM building

awk 'BEGIN { FS = " *= *" }
	NF != 2 { next }
	$1 == "VERSION" { maj = $2 }
	$1 == "PATCHLEVEL" { mid = $2 }
	$1 == "SUBLEVEL" { min = $2 }
	$1 == "EXTRAVERSION" { ext = $2 }
	END { print maj "." mid "." min ext }' $*
