





#include "asn1.h"





mapping_t asn1_type_m[] = {
	{ASN1_END, "ASN1_END"},
	{ASN1_BOOLEAN, "ASN1_BOOLEAN"},
	{ASN1_INTEGER, "ASN1_INTEGER"},
	{ASN1_BIT_STRING, "ASN1_BIT_STRING"},
	{ASN1_OCTET_STRING, "ASN1_OCTET_STRING"},
	{ASN1_NULL, "ASN1_NULL"},
	{ASN1_OID, "ASN1_OID"},
	{ASN1_ENUMERATED, "ASN1_ENUMERATED"},
	{ASN1_UTF8STRING, "ASN1_UTF8STRING"},
	{ASN1_NUMERICSTRING, "ASN1_NUMERICSTRING"},
	{ASN1_PRINTABLESTRING, "ASN1_PRINTABLESTRING"},
	{ASN1_T61STRING, "ASN1_T61STRING"},
	{ASN1_VIDEOTEXSTRING, "ASN1_VIDEOTEXSTRING"},
	{ASN1_IA5STRING, "ASN1_IA5STRING"},
	{ASN1_UTCTIME, "ASN1_UTCTIME"},
	{ASN1_GENERALIZEDTIME, "ASN1_GENERALIZEDTIME"},
	{ASN1_GRAPHICSTRING, "ASN1_GRAPHICSTRING"},
	{ASN1_VISIBLESTRING, "ASN1_VISIBLESTRING"},
	{ASN1_GENERALSTRING, "ASN1_GENERALSTRING"},
	{ASN1_UNIVERSALSTRING, "ASN1_UNIVERSALSTRING"},
	{ASN1_BMPSTRING, "ASN1_BMPSTRING"},
	{ASN1_CONSTRUCTED, "ASN1_CONSTRUCTED"},
	{ASN1_SEQUENCE, "ASN1_SEQUENCE"},
	{ASN1_SET, "ASN1_SET"},
	{ASN1_TAG_E_0, "ASN1_TAG_E_0"},
	{ASN1_TAG_E_1, "ASN1_TAG_E_1"},
	{ASN1_TAG_E_2, "ASN1_TAG_E_2"},
	{ASN1_TAG_E_3, "ASN1_TAG_E_3"},
	{ASN1_TAG_E_4, "ASN1_TAG_E_4"},
	{ASN1_TAG_E_5, "ASN1_TAG_E_5"},
	{ASN1_TAG_E_6, "ASN1_TAG_E_6"},
	{ASN1_TAG_E_7, "ASN1_TAG_E_7"},
	{ASN1_TAG_I_1, "ASN1_TAG_I_1"},
	{ASN1_TAG_I_2, "ASN1_TAG_I_2"},
	{ASN1_TAG_I_3, "ASN1_TAG_I_3"},
	{ASN1_TAG_I_4, "ASN1_TAG_I_4"},
	{ASN1_TAG_I_5, "ASN1_TAG_I_5"},
	{ASN1_TAG_I_6, "ASN1_TAG_I_6"},
	{ASN1_TAG_I_7, "ASN1_TAG_I_7"},
};

mapping_t asn1_flag_m[] = {
	{ASN1_OPTIONAL, "ASN1_OPTIONAL"},
	{ASN1_DEFAULT, "ASN1_DEFAULT"},
	{ASN1_MPZ, "ASN1_MPZ"},
	{ASN1_OF, "ASN1_OF"},
};
