name: lgtm.com

on: [push]

env:
  OS_NAME: linux

jobs:
  pre-check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip-check.outputs.should_skip }}
    steps:
      - id: skip-check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'

  lgtm:
    needs: pre-check
    if: ${{ needs.pre-check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    env:
      TEST: lgtm
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # we don't use github/codeql-action because we can't exclude queries there,
      # so we continue to use the approach we used on Travis
      - env:
          LGTM_TOKEN: ${{ secrets.LGTM_TOKEN }}
          LGTM_PROJECT: ${{ secrets.LGTM_PROJECT }}
          BUILD_NUMBER: ${{ github.run_id }}
          COMMIT_ID: ${{ github.sha }}
          COMMIT_BASE: ${{ github.event.before }}
        uses: ./.github/actions/default
